site_name: GPTQuery
docs_dir: docs

theme:
  name: material
  logo: assets/robot-talking.png
  favicon: assets/robot-talking.ico
  features:
    - search.suggest
  font:
    text: Roboto
    code: JetBrains Mono
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: cyan          # top bar color
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: cyan
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Developers Guide: devsquickstart.md
  # - Advanced Usage: advanced_usage.md
  - 🧰 Tools:
    - EU Law Citations: tools/eulaw_citations.md
    - Classify EU Legal Text: tools/classify_text.md
    - Extract Entities: tools/text_extraction.md

extra_css:
  - stylesheets/overrides.css

plugins:
  - search